#https://github.com/ory/examples/blob/master/full-stack/docker-compose.yml
#https://github.com/google/trillian/issues/1164

version: '3'
services:
  demo:
    image: django_demo:dev
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=yetongxue
      - MYSQL_DATABASE=django_demo
      - MYSQL_PASSWORD=qwerasdf
    ports:
      - 8000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=yetongxue
      - MYSQL_PASSWORD=qwerasdf
      - MYSQL_DATABASE=django_demo
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
